export const state = {
  photos: [],
  currentPage: 1,
  totalPages: 0,
  total: 0,
  perPage: 60,
  loading: false,
  activeFilter: "all",
  activeLocation: null,
  activeCountry: null,
  activeCity: null,
  dateFrom: null,
  dateTo: null,
  searchQuery: "",
  modalPhotoIndex: -1,
  scanComplete: false,
  timeline: [],
  locations: [],
  language: "zh",
  theme: "light",
  loadOriginalOnClick: false,
  expandedMonths: new Set(),
  expandedCountries: new Set()
};
